# Generated by Django 3.2.4 on 2021-06-25 01:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto_marca_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProductoMarca',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='')),
                ('primera', models.BooleanField(default=False)),
                ('producto_marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto_marca_app.productomarca')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
