from .inicio import admin_inicio
from .registro import registro
from .bodega import generar_csv, admin_bodega_agregar, admin_bodega_eliminar, admin_bodega_inicio, admin_bodega_modificar
from .proveedor import admin_proveedor_eliminar, admin_proveedor_inicio, admin_proveedor_agregar, admin_proveedor_modificar
from .seccion import admin_seccion_agregar, admin_seccion_eliminar, admin_seccion_inicio, admin_seccion_modificar
from .coleccion import admin_coleccion_agregar, admin_coleccion_eliminar, admin_coleccion_inicio, admin_coleccion_modificar
from .producto_bodega import admin_producto_bodega_inicio, admin_producto_bodega_agregar
from .producto_bodega_detalle import admin_producto_bodega_detalle_agregar, admin_producto_bodega_detalle_listar_talla, admin_producto_bodega_detalle_listar_color,  \
    admin_producto_bodega_detalle_listar_estado, admin_producto_bodega_reporte,ReportPBView
from .producto_marca import admin_producto_marca_inicio, admin_producto_marca_agregar
from .producto_bodega_marca import admin_producto_bodega_marca_agregar, admin_producto_bodega_marca_agregar_detalle, admin_producto_bodega_marca_eliminar_detalle_
from .imagen_producto_marca import admin_producto_bodega_marca_agregar_imagen, admin_producto_bodega_marca_listar_imagen, admin_producto_bodega_marca_eliminar, admin_producto_bodega_marca_eliminar_detalle
