# Generated by Django 3.2.4 on 2021-06-25 01:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coleccion_app', '0001_initial'),
        ('seccion_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoMarca',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('utilidad', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('descuento', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('unidad_minima_descuento', models.IntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coleccion_app.coleccion')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seccion_app.seccion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
