# Generated by Django 3.2.4 on 2021-06-25 01:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto_bodega_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoBodegaDetalle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('talla', models.CharField(choices=[['0-2', '0-2'], ['2-4', '2-4'], ['6-8', '6-8'], ['10-12', '10-12'], ['14-16', '14-16'], ['XS', 'XS'], ['S', 'S'], ['M', 'M'], ['L', 'L'], ['XL', 'XL'], ['XXL', 'XXL'], ['XXXL', 'XXXL']], max_length=6)),
                ('color', models.CharField(choices=[['#FFEC33', 'AMARILLO'], ['#09619a', 'AZUL'], ['#FF3333', 'ROJO'], ['#FFFFFF', 'BLANCO'], ['#000000', 'NEGRO'], ['#349C18', 'VERDE'], ['#0a2e47', 'AZUL MARCA'], ['#d9d8d8', 'GRIS MARCA']], max_length=7)),
                ('estado', models.CharField(choices=[['OK', 'OK'], ['DF', 'DEFECTUOSO'], ['PD', 'PARCIALMENTE DAÑADO'], ['CD', 'COMPLETAMENTE DAÑADO'], ['ND', 'NO DECEADO'], ['NE', 'NO ESPERADO']], max_length=2)),
                ('informacion', models.TextField()),
                ('producto_bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto_bodega_app.productobodega')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
