# Generated by Django 3.2.4 on 2021-06-25 01:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega_app', '0001_initial'),
        ('proveedor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoBodega',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad_entra', models.PositiveIntegerField(default=0)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('cantidad_minima', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('is_relacionado', models.BooleanField(default=False)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodega_app.bodega')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor_app.proveedor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
